 <form class="decor">
  <div class="form-left-decoration"></div>
  <div class="form-right-decoration"></div>
  <div class="circle"></div>
  <div class="form-inner">
    <h1>SpaceChat</h1>
    <div class="messages">
        <?php require __DIR__ . '/chatpagemessages.phtml'; ?>
    </div>
    <textarea id="common_text" placeholder="Сообщение..." rows="3"></textarea>
    <input type="button" id="common_submit" value="Отправить"/>
  </div>