<!DOCTYPE html>
<html lang="ru">
<head>
  <title>SpaceChat</title>
  <!-- подключение стилей -->
  <link rel="stylesheet" href="area.css">
  <link rel="stylesheet" href="main.css">
  <!-- подключение скриптов -->
    <script type="text/javascript" src="scripts/jquery-3.3.1.min.js" ></script>
    <script type="text/javascript" src="scripts/main.js"></script>
</head>
<body>
  <div class="canvas">
  <div class="earth">
    <div class="land-big na">
      <div class="land l-1"></div>
      <div class="land-join"></div>
      <div class="land l-2"></div>
    </div>
    <div class="land-big sa">
      <div class="land l-1"></div>
      <div class="land-join"></div>
      <div class="land l-2"></div>
    </div>
    <div class="land-big ce">
      <div class="land l-1"></div>
      <div class="land-join"></div>
      <div class="land-join j-2"></div>
      <div class="land l-2"></div>
      <div class="land l-3"></div>
    </div>
    <div class="land-big a">
      <div class="land l-1"></div>
      <div class="land-join"></div>
      <div class="land l-2"></div>
    </div>
    <div class="land ne"></div>
    <div class="land au"></div>
    <div class="land np"></div>
    <div class="land sp"></div>
    <div class="cloud-wrapper">
      <div class="cloud c1"></div>
      <div class="cloud c2"></div>
      <div class="cloud c3"></div>
      <div class="cloud c4"></div>  
      <div class="cloud c5"></div>  
      <div class="cloud c6"></div>  
      <div class="cloud c7"></div>  
      <div class="cloud c8"></div>  
    </div>
  </div>
  <div class="shine"></div>
  <div class="ellipsis">
    <div class="rotate-moon">
      <div class="counter-rotate-moon">
        <div class="moon">
          <div class="crater c1"></div>
          <div class="crater c2"></div>
          <div class="crater c3"></div>
          <div class="crater c4"></div>
        </div>
      </div>
    </div>
  </div>
</div>

 <div class="wrapper">
    <?php if($pageName == 'login') require __DIR__ . '/loginpage/loginpagecontent.phtml'; ?>
    <?php if($pageName == 'chat') require __DIR__ . '/chatpage/chatpagewrap.phtml'; ?>
</div>

<footer>
    <a href="index.php?loginpage=true">Авторизация</a>
</footer>
</body>
</html>